font_family JetBrains Mono
font_size 11.0
background #101216
foreground #f0f3f7
selection_background #ff3344
selection_foreground #ffffff
cursor #ff3344
cursor_shape beam
window_padding_width 8
confirm_os_window_close 0
hide_window_decorations yes
linux_display_server x11
enable_audio_bell no
scrollback_lines 10000
shell_integration enabled
